### ISSUE TITLE
How can i use an evolved type system only?

### ISSUE THREAD

**Issue by ktlsn1234** [openai/deeptype#52]
Hello,
I have a question about using discovered type system (e.g. cem, greedy, ga ..)

I train type classifier with discovered type system(from evolve_type_system) using train config from TypeSystemToNeuralTypeSystem.ipynb.
but at prediction time, there is no 'type' in get_prob() at learning/SentencePredictions.ipynb.

I guess it seems because discovered type system does not include type classification.

How should the get_prob() be when i use only discovered type system?

**Comment by JonathanRaiman** [comment]
If you look a the JSON for your training of the discovered type system, each type axis has a name (`surname` in ```typename = types["qid"]
        relation = types["relation"]
        surname = typename + "_" + relation.replace(" ", "_")``` from `TypeSystemToNeuralTypeSystem.ipynb`). This is the axis you have access to and can query. I recommend looking for probabilities programmatically rather than retyping the names (e.g. look at the model's objectives field for the names of the axes).
